"""empty message

Revision ID: b0962321a4be
Revises: cef9149ac813
Create Date: 2023-09-10 22:21:47.706682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0962321a4be'
down_revision: Union[str, None] = 'cef9149ac813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('syncdirs', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'syncdirs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'syncdirs', type_='foreignkey')
    op.drop_column('syncdirs', 'user_id')
    # ### end Alembic commands ###
